# interactive version of LLM-assisted lifter

# 在85-86行，定义了json输出的形式
# 在120-125行，对返回结果做了json化处理，并提取出提升结果直接存到tmpfiles中的*.ll文件中

from openai import OpenAI
import openai
from pydantic import BaseModel
import json
import subprocess
import sys
import os
import time
import argparse
from utils import generate_feedback_prompt_v2, replace_line_in_file
from utils import FixType, ErrorType, ClangError
from utils import LLMLifterConfig
# from utils import data_preprocess, data_fix
from utils import DataPreprocess
# from utils import extract_error_line
# import extract_function_asm

class LiftJsonOutput(BaseModel):
    lift_json: str

if __name__ == '__main__':
    config = LLMLifterConfig.parse_arguments()
    print(config)
    
    tmpfile_dir = f"{config.test_dir}/{config.tmpfile_dir}"

    if config.lift_func:
        function_asm = f"{tmpfile_dir}/{config.binary}.{config.lift_func}.x86_asm"
        # function_asm = f"{tmpfile_dir}/{config.binary}.x86_asm"
    else:
        function_asm = f"{tmpfile_dir}/{config.binary}.x86_asm"
    if not os.path.isfile(function_asm):
        raise FileNotFoundError(f"file {function_asm} not exist")

    liftfunc_suffix = "" if not config.lift_func else f".{config.lift_func}"

    gpt_function_ll = f"{tmpfile_dir}/{config.binary}{liftfunc_suffix}-llm-dis.ll"
    gpt_function_bin = f"{tmpfile_dir}/{config.binary}{liftfunc_suffix}-llm-dis.o"
    prompts_save_file_prefix = f"{config.test_dir}/prompts/{config.binary}{liftfunc_suffix}.pmt"
    gpt_function_save_file_prefix = f"{config.test_dir}/gpt_functions/{config.binary}{liftfunc_suffix}-llm-dis"
    error_msg_save_file_prefix = f"{config.test_dir}/err_msgs/{config.binary}{liftfunc_suffix}.err"
    success_turn_save_file = f"{config.test_dir}/iter_times/{config.binary}{liftfunc_suffix}.iter"

    with open(function_asm, "r") as f:
        code = f.read()
    print(f"read function assembly code from {function_asm}")

    proto_file = f"{config.test_dir}/scripts/func_proto.txt"
    with open(proto_file, "r") as f:
        protos = f.read()

    init_prompts = [
        {
            "role": "system",
            "content": """ You will be provided with x86-64 assembly code (generated by IDAPro) about a program (denoted by <code> tag).
            The disassembly of the binary program consists of multiple sections:
                1. <constant> stores constants like string constants, floating-point numbers and integers.
                2. <global> declares global variables initialized at the program start.
                3. <extern> references external entities.
                4. <func> encapsulates functions, including their local variables, stack operations, control flow with unconditional/conditional branches and function call.
            Lift the assembly code to LLVM IR. Do not explain anything and include any extra instructions, only print LLVM IR.
            Output Format Requirements:
            1. Only need to declare functions that do not appear in the assembly code.
            """
            # Output Format Requirements:
            #     1. All floating-point constants are represented in hexadecimal format.
            #     2. If the return type of a function is not void, its return value must be represented by an SSA variable.
            #     e.g., %N = call i32 () @function(), in which %N is an SSA variable.
            #     3. If the return type of a translation function is not void, its return value must NOT be represented by an SSA variable.
            #     e.g., `call void () @function()` is correct but `%N = call void () @function()` is wrong
            #     4. All integer constants should be represented in hexadecimal format and prefixed with u.
            #     e.g., 0x123456 is an integer constant in assembly code. 
            #     In generated LLVM IR, being represented as `u0x123456` is correct, but as `0x123456` is wrong, 
            #     for hexadecimal numbers without any prefix represent floating-point values in LLVM IR.
        },
        {
            "role": "user",
            "content": f"""<code> {code} </code>"""
        },
    ]

    prompts = init_prompts

    client = OpenAI()
    openai.api_request_timeout = 10000  # 超时时间为10000s
    time_start = time.time()

    # 生成初始结果
    print("===========================================")
    print("Generating initial lifting results...")

    response_result = client.beta.chat.completions.parse(
        # model='ft:gpt-4o-2024-08-06:personal::AfjYou2F',
        model=config.model_name,
        messages=prompts,
        response_format=LiftJsonOutput,
        temperature=config.temperature,
    )

    print(f"Get response from model {config.model_name}")
    data = json.loads(response_result.choices[0].message.content)
    llvm_ir = data["lift_json"]

    # 处理常见错误
    print("Preprocessing the generated LLVM IR...")
    data_preprocessor = DataPreprocess(llvm_ir)
    data_preprocessor.fix_format()
    data_preprocessor.fix_call()
    llvm_ir = data_preprocessor.get_llvm_str()

    # ================= 中间文件保存 =====================
    gpt_function_save_file = gpt_function_save_file_prefix + ".0.ll"
    with open(gpt_function_save_file, "w") as f:
        f.write(llvm_ir)
    print(f"Initial lifting results have been saved to {gpt_function_save_file} and {gpt_function_ll}")
    
    prompts_save_file = f"{prompts_save_file_prefix}.0.json"
    with open(prompts_save_file, "w", encoding='utf-8') as f:
        json.dump(prompts, f, ensure_ascii=False, indent=4)
    print(f"Initial prompt has been saved to {prompts_save_file}")
    # ===================================================

    with open(gpt_function_ll, "w") as f:
        f.write(llvm_ir)

    # prompts += [{
    #     "role": "assistant",
    #     "content": llvm_ir
    # }]

    # 进行自修正

    init_prompts_fix = [{
        "role": "system",
        "content": """ You are an assistant for correcting LLVM IR errors. \
            Please fix the errors based on the provided error location and error message. \
            Only print fixed LLVM IR."""
        },
        {
        "role": "user",
        "content": f"""The erroneous LLVM IR is as follows: {llvm_ir}"""
        },
    ]

    prompts = init_prompts_fix

    turn = 0
    while turn < config.max_turn:
        # ===================== Verifer =========================
        # 获取编译报错信息
        print("Compiling generated .ll file to executable file...")
        cmd = [
            "clang",
            "-c", # 生成目标文件，因为可能存在外部变量/函数引用
            gpt_function_ll,
            "-w", # ignore warning
            "-o",
            gpt_function_bin,
        ]
        compile_result = subprocess.run(cmd, capture_output=True, text=True)

        # 处理报错信息
        if compile_result.returncode == 0:
            print(f"Compile succeed at Turn {turn} fixing, save compiled binary in: {gpt_function_bin}")
            with open(success_turn_save_file, "w") as f:
                f.write(str(turn))
            break
        print(f"Failed to compile, get error message:\n{compile_result.stderr}")
        error_message = ClangError.parse(compile_result.stderr.splitlines()[0])
        if error_message == None:
            print(f"Failed to parse: {compile_result.stderr}")
            exit(-1)
        # ===================== Verifer =========================


        # ===================== Self Fixing ========================
        print("Generating feedback prompt according to error message...")
        # 根据报错信息生成反馈
        feedback_prompt = generate_feedback_prompt_v2(
            ErrorType.CompileError, error_message, config.fix_type, llvm_ir
        )
        prompts += feedback_prompt

        # 自修正
        turn = turn + 1

        print("===========================================")
        print(f"Turn {turn} fixing...")
        print(f"Fixtype is {config.fix_type.name}")

        response_result = client.beta.chat.completions.parse(
            # model=config.model_name,
            model='ft:gpt-4o-2024-08-06:personal::AfjYou2F',
            messages=prompts,
            response_format=LiftJsonOutput,
            temperature=config.temperature,
        )

        print(f"Get response from model {config.model_name}")


        data = json.loads(response_result.choices[0].message.content)
        llvm_ir = data["lift_json"]

        # 处理常见错误
        print("Preprocessing the generated LLVM IR...")
        data_preprocessor = DataPreprocess(llvm_ir)
        data_preprocessor.fix_format()
        # data_preprocessor.fix_call()
        llvm_ir = data_preprocessor.get_llvm_str()

        if config.fix_type == FixType.File:
            with open(gpt_function_ll, "w") as f:
                f.write(llvm_ir)
        elif config.fix_type == FixType.Func:
            print("not supported fix-type: Func")
            continue
        elif config.fix_type == FixType.Line:
            replace_line_in_file(gpt_function_ll, error_message.line, llvm_ir)

        prompts += [{
            "role": "assistant",
            "content": llvm_ir
        }]

        print(f"Fixing results have been saved to {gpt_function_ll}")
        # ===================== Self Fixing ========================


        # =================== 中间文件保存 =============================
        print("Saving intermediate files...")
        # 保存大模型的回答
        gpt_function_save_file = f"{gpt_function_save_file_prefix}.{turn}.ll"
        with open(gpt_function_save_file, "w") as f:
            f.write(llvm_ir)
        print(f"LLM response has been saved to {gpt_function_save_file}")

        # 保存每轮的feedback prompt
        prompts_save_file = f"{prompts_save_file_prefix}.{turn}.json"
        with open(prompts_save_file, "w", encoding='utf-8') as f:
            json.dump(feedback_prompt, f, ensure_ascii=False, indent=4)
        print(f"Feedback prompt has been saved to {prompts_save_file}")

        # 保存每轮的error message
        error_msg_save_file = f"{error_msg_save_file_prefix}.{turn}"
        with open(error_msg_save_file, "w") as f:
            f.write(compile_result.stderr)
        print(f"Error message has been saved to {error_msg_save_file}")

        # 保存每轮的turn
        with open(success_turn_save_file, "w") as f:
            f.write(str(turn))
        # # save response in responses/
        # with open(response_save_file + "." + str(turn), "w") as f:
        #     f.write(str(response_result))
        # # save generated LLVM IR in gpt_function_ir/
        # with open(gpt_function_save_file + "." + str(turn) + ".ll", "w") as f:
        #     f.write(response_result.choices[0].message.content)

        # save generated LLVM IR to gpt_funcion.ll for further processing
        # =============================================================

        # input("Press any key to continue...")
        # =================== 中间文件保存 =============================

    time_end = time.time()
    print("time cost ", time_end - time_start, "s")